//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Appraisal.Module.BusinessObjects.Appraisaldb
{

    public partial class objective_next_year : XPLiteObject
    {
        string fbase_start_point;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Base Start Point")]
        public string base_start_point
        {
            get { return fbase_start_point; }
            set { SetPropertyValue<string>("base_start_point", ref fbase_start_point, value); }
        }
        string fmethod_actions;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Method Actions")]
        public string method_actions
        {
            get { return fmethod_actions; }
            set { SetPropertyValue<string>("method_actions", ref fmethod_actions, value); }
        }
        string fobjective;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Objective")]
        public string objective
        {
            get { return fobjective; }
            set { SetPropertyValue<string>("objective", ref fobjective, value); }
        }
        int fObjective_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int Objective_id
        {
            get { return fObjective_id; }
            set { SetPropertyValue<int>("Objective_id", ref fObjective_id, value); }
        }
        personnel_master fpersonnel_id;
        [Indexed(Name = @"personnel_id")]
        [Association(@"objective_next_yearReferencespersonnel_master")]
        [DevExpress.Xpo.DisplayName(@"Personnel")]
        public personnel_master personnel_id
        {
            get { return fpersonnel_id; }
            set { SetPropertyValue<personnel_master>("personnel_id", ref fpersonnel_id, value); }
        }
        short frating;
        [DevExpress.Xpo.DisplayName(@"Rating")]
        public short rating
        {
            get { return frating; }
            set { SetPropertyValue<short>("rating", ref frating, value); }
        }
        DateTime ftiming_to_complete;
        [DevExpress.Xpo.DisplayName(@"Timing To Complete")]
        public DateTime timing_to_complete
        {
            get { return ftiming_to_complete; }
            set { SetPropertyValue<DateTime>("timing_to_complete", ref ftiming_to_complete, value); }
        }
    }

}
