//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Appraisal.Module.BusinessObjects.Appraisaldb
{

    public partial class personnel_master : XPLiteObject
    {
        string fACCOUNTABILITY_EVIDENCE;
        [Size(SizeAttribute.Unlimited)]
        public string ACCOUNTABILITY_EVIDENCE
        {
            get { return fACCOUNTABILITY_EVIDENCE; }
            set { SetPropertyValue<string>("ACCOUNTABILITY_EVIDENCE", ref fACCOUNTABILITY_EVIDENCE, value); }
        }
        short fACCOUNTABILITY_RATING;
        [DevExpress.Xpo.DisplayName(@"ACCOUNTABILITY RATING")]
        public short ACCOUNTABILITY_RATING
        {
            get { return fACCOUNTABILITY_RATING; }
            set { SetPropertyValue<short>("ACCOUNTABILITY_RATING", ref fACCOUNTABILITY_RATING, value); }
        }
        double fACCOUNTABILITY_Weight;
        [DevExpress.Xpo.DisplayName(@"ACCOUNTABILITY Weight")]
        public double ACCOUNTABILITY_Weight
        {
            get { return fACCOUNTABILITY_Weight; }
            set { SetPropertyValue<double>("ACCOUNTABILITY_Weight", ref fACCOUNTABILITY_Weight, value); }
        }
        string fappraisee_comments;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Appraisee Comments")]
        public string appraisee_comments
        {
            get { return fappraisee_comments; }
            set { SetPropertyValue<string>("appraisee_comments", ref fappraisee_comments, value); }
        }
        string fCONSUMER_FOCUSED_EVIDENCE;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"CONSUMER FOCUSED EVIDENCE")]
        public string CONSUMER_FOCUSED_EVIDENCE
        {
            get { return fCONSUMER_FOCUSED_EVIDENCE; }
            set { SetPropertyValue<string>("CONSUMER_FOCUSED_EVIDENCE", ref fCONSUMER_FOCUSED_EVIDENCE, value); }
        }
        short fCONSUMER_FOCUSED_RATING;
        [DevExpress.Xpo.DisplayName(@"CONSUMER FOCUSED RATING")]
        public short CONSUMER_FOCUSED_RATING
        {
            get { return fCONSUMER_FOCUSED_RATING; }
            set { SetPropertyValue<short>("CONSUMER_FOCUSED_RATING", ref fCONSUMER_FOCUSED_RATING, value); }
        }
        double fCONSUMER_FOCUSED_Weight;
        [DevExpress.Xpo.DisplayName(@"CONSUMER FOCUSED Weight")]
        public double CONSUMER_FOCUSED_Weight
        {
            get { return fCONSUMER_FOCUSED_Weight; }
            set { SetPropertyValue<double>("CONSUMER_FOCUSED_Weight", ref fCONSUMER_FOCUSED_Weight, value); }
        }
        string femp_past_year_description_appraisee;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Employee past year description appraisee")]
        public string emp_past_year_description_appraisee
        {
            get { return femp_past_year_description_appraisee; }
            set { SetPropertyValue<string>("emp_past_year_description_appraisee", ref femp_past_year_description_appraisee, value); }
        }
        short femp_rating;
        [DevExpress.Xpo.DisplayName(@"Employee Rating")]
        public short emp_rating
        {
            get { return femp_rating; }
            set { SetPropertyValue<short>("emp_rating", ref femp_rating, value); }
        }
        string fENTREPRENEURIAL_LEADERSHIP_EVIDENCE;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"ENTREPRENEURIAL LEADERSHIP EVIDENCE")]
        public string ENTREPRENEURIAL_LEADERSHIP_EVIDENCE
        {
            get { return fENTREPRENEURIAL_LEADERSHIP_EVIDENCE; }
            set { SetPropertyValue<string>("ENTREPRENEURIAL_LEADERSHIP_EVIDENCE", ref fENTREPRENEURIAL_LEADERSHIP_EVIDENCE, value); }
        }
        short fENTREPRENEURIAL_LEADERSHIP_RATING;
        [DevExpress.Xpo.DisplayName(@"ENTREPRENEURIAL LEADERSHIP RATING")]
        public short ENTREPRENEURIAL_LEADERSHIP_RATING
        {
            get { return fENTREPRENEURIAL_LEADERSHIP_RATING; }
            set { SetPropertyValue<short>("ENTREPRENEURIAL_LEADERSHIP_RATING", ref fENTREPRENEURIAL_LEADERSHIP_RATING, value); }
        }
        double fENTREPRENEURIAL_LEADERSHIP_Weight;
        [DevExpress.Xpo.DisplayName(@"ENTREPRENEURIAL LEADERSHIP Weight")]
        public double ENTREPRENEURIAL_LEADERSHIP_Weight
        {
            get { return fENTREPRENEURIAL_LEADERSHIP_Weight; }
            set { SetPropertyValue<double>("ENTREPRENEURIAL_LEADERSHIP_Weight", ref fENTREPRENEURIAL_LEADERSHIP_Weight, value); }
        }
        string fjob_description;
        [Size(255)]
        [DevExpress.Xpo.DisplayName(@"Job Description")]
        public string job_description
        {
            get { return fjob_description; }
            set { SetPropertyValue<string>("job_description", ref fjob_description, value); }
        }
        string fjob_name;
        [Size(255)]
        [DevExpress.Xpo.DisplayName(@"Job Name")]
        public string job_name
        {
            get { return fjob_name; }
            set { SetPropertyValue<string>("job_name", ref fjob_name, value); }
        }
        int fmanager_id;
        [Indexed(Name = @"emp_manager_id")]
        [DevExpress.Xpo.DisplayName(@"Manager ID")]
        public int manager_id
        {
            get { return fmanager_id; }
            set { SetPropertyValue<int>("manager_id", ref fmanager_id, value); }
        }
        string fmanager_name;
        [Size(255)]
        [DevExpress.Xpo.DisplayName(@"Manager Name")]
        public string manager_name
        {
            get { return fmanager_name; }
            set { SetPropertyValue<string>("manager_name", ref fmanager_name, value); }
        }
        string fmanager_past_year_description_appraisee;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Manager Past Year Description Appraisee")]
        public string manager_past_year_description_appraisee
        {
            get { return fmanager_past_year_description_appraisee; }
            set { SetPropertyValue<string>("manager_past_year_description_appraisee", ref fmanager_past_year_description_appraisee, value); }
        }
        short fmanager_rating;
        [DevExpress.Xpo.DisplayName(@"Manager Rating")]
        public short manager_rating
        {
            get { return fmanager_rating; }
            set { SetPropertyValue<short>("manager_rating", ref fmanager_rating, value); }
        }
        string fPERFORMANCE_EVIDENCE;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"PERFORMANCE EVIDENCE")]
        public string PERFORMANCE_EVIDENCE
        {
            get { return fPERFORMANCE_EVIDENCE; }
            set { SetPropertyValue<string>("PERFORMANCE_EVIDENCE", ref fPERFORMANCE_EVIDENCE, value); }
        }
        short fPERFORMANCE_RATING;
        [DevExpress.Xpo.DisplayName(@"PERFORMANCE RATING")]
        public short PERFORMANCE_RATING
        {
            get { return fPERFORMANCE_RATING; }
            set { SetPropertyValue<short>("PERFORMANCE_RATING", ref fPERFORMANCE_RATING, value); }
        }
        double fPERFORMANCE_Weight;
        [DevExpress.Xpo.DisplayName(@"PERFORMANCE Weight")]
        public double PERFORMANCE_Weight
        {
            get { return fPERFORMANCE_Weight; }
            set { SetPropertyValue<double>("PERFORMANCE_Weight", ref fPERFORMANCE_Weight, value); }
        }
        int fpersonnel_id;
        [Key]
        [DevExpress.Xpo.DisplayName(@"Personnel ID")]
        public int personnel_id
        {
            get { return fpersonnel_id; }
            set { SetPropertyValue<int>("personnel_id", ref fpersonnel_id, value); }
        }
        string fpersonnel_name;
        [Size(255)]
        [DevExpress.Xpo.DisplayName(@"Personnel Name")]
        public string personnel_name
        {
            get { return fpersonnel_name; }
            set { SetPropertyValue<string>("personnel_name", ref fpersonnel_name, value); }
        }
        string fpossible_career_development_emp;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Possible Career Development (Employee)")]
        public string possible_career_development_emp
        {
            get { return fpossible_career_development_emp; }
            set { SetPropertyValue<string>("possible_career_development_emp", ref fpossible_career_development_emp, value); }
        }
        string fpossible_career_development_how;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Possible Career Development (How)")]
        public string possible_career_development_how
        {
            get { return fpossible_career_development_how; }
            set { SetPropertyValue<string>("possible_career_development_how", ref fpossible_career_development_how, value); }
        }
        string fpossible_career_development_manager;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Possible Career Development (Manager)")]
        public string possible_career_development_manager
        {
            get { return fpossible_career_development_manager; }
            set { SetPropertyValue<string>("possible_career_development_manager", ref fpossible_career_development_manager, value); }
        }
        string fQUALITY_EVIDENCE;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"QUALITY EVIDENCE")]
        public string QUALITY_EVIDENCE
        {
            get { return fQUALITY_EVIDENCE; }
            set { SetPropertyValue<string>("QUALITY_EVIDENCE", ref fQUALITY_EVIDENCE, value); }
        }
        short fQUALITY_RATING;
        [DevExpress.Xpo.DisplayName(@"QUALITY RATING")]
        public short QUALITY_RATING
        {
            get { return fQUALITY_RATING; }
            set { SetPropertyValue<short>("QUALITY_RATING", ref fQUALITY_RATING, value); }
        }
        double fQUALITY_Weight;
        [DevExpress.Xpo.DisplayName(@"QUALITY Weight")]
        public double QUALITY_Weight
        {
            get { return fQUALITY_Weight; }
            set { SetPropertyValue<double>("QUALITY_Weight", ref fQUALITY_Weight, value); }
        }
        DateTime freview_date;
        [DevExpress.Xpo.DisplayName(@"Review Date")]
        public DateTime review_date
        {
            get { return freview_date; }
            set { SetPropertyValue<DateTime>("review_date", ref freview_date, value); }
        }
        string fTEAM_WORK_EVIDENCE;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"TEAM WORK EVIDENCE")]
        public string TEAM_WORK_EVIDENCE
        {
            get { return fTEAM_WORK_EVIDENCE; }
            set { SetPropertyValue<string>("TEAM_WORK_EVIDENCE", ref fTEAM_WORK_EVIDENCE, value); }
        }
        short fTEAM_WORK_RATING;
        [DevExpress.Xpo.DisplayName(@"TEAM WORK RATING")]
        public short TEAM_WORK_RATING
        {
            get { return fTEAM_WORK_RATING; }
            set { SetPropertyValue<short>("TEAM_WORK_RATING", ref fTEAM_WORK_RATING, value); }
        }
        double fTEAM_WORK_Weight;
        [DevExpress.Xpo.DisplayName(@"TEAM WORK Weight")]
        public double TEAM_WORK_Weight
        {
            get { return fTEAM_WORK_Weight; }
            set { SetPropertyValue<double>("TEAM_WORK_Weight", ref fTEAM_WORK_Weight, value); }
        }
        string ftime_in_current_role;
        [Size(255)]
        [DevExpress.Xpo.DisplayName(@"Time In Current Role")]
        public string time_in_current_role
        {
            get { return ftime_in_current_role; }
            set { SetPropertyValue<string>("time_in_current_role", ref ftime_in_current_role, value); }
        }
        string ffile_path;
        [Size(SizeAttribute.Unlimited)]
        [DevExpress.Xpo.DisplayName(@"File Path")]
        [ReadOnly(true)]
        public string file_path
        {
            get { return ffile_path; }
            set { SetPropertyValue<string>("file_path", ref ffile_path, value); }
        }
        DateTime flast_update_date;
        [DevExpress.Xpo.DisplayName(@"Last Update Date")]
        [ReadOnly(true)]
        public DateTime last_update_date
        {
            get { return flast_update_date; }
            set { SetPropertyValue<DateTime>("last_update_date", ref flast_update_date, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Developments")]
        [Association(@"developmentReferencespersonnel_master")]
        public XPCollection<development> developments { get { return GetCollection<development>("developments"); } }
        [DevExpress.Xpo.DisplayName(@"Objectives")]
        [Association(@"objectiveReferencespersonnel_master")]
        public XPCollection<objective> objectives { get { return GetCollection<objective>("objectives"); } }
        [DevExpress.Xpo.DisplayName(@"Objective Next Years")]
        [Association(@"objective_next_yearReferencespersonnel_master")]
        public XPCollection<objective_next_year> objective_next_years { get { return GetCollection<objective_next_year>("objective_next_years"); } }
    }

}
